apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubernetes-prometheus-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Gi
  selector:
    matchLabels:
      pv: kubernetes-prometheus-pv