apiVersion: v1
kind: PersistentVolume
metadata:
  name: genoany-dev-mysql1-cephrbd-pv
  labels:
    pv: genoany-dev-mysql1-cephrbd-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  rbd:
    monitors:
      - 192.168.1.7:6789
      - 192.168.1.17:6789
      - 192.168.1.37:6789
    pool: rbd
    image: k8s-genoany-dev
    user: admin
    secretRef:
      name: cephfs-secret
    fsType: ext4
    readOnly: false